### ISSUE TITLE
Update/Sync project wrt origin

### ISSUE THREAD

**Issue by sacOO7** [ably-forks/laravel-echo#21]
- Need to sync the project with https://github.com/laravel/echo
- Need to introduce new function that leaves all channels https://github.com/laravel/echo/pull/365
- Check support for encrypted channels https://ably.com/docs/realtime/encryption?lang=javascript

**Comment by aasiph** [comment]
@sacOO7 What i am trying to say is that the types path in package.json is **"types": "dist/echo.d.ts"**. where as i see all typings declaration files in **"dist/src/"**

Check below image.
![Code_MzSaQRFAom](https://user-images.githubusercontent.com/312443/231389195-1a16a8c2-046b-4176-b8e8-afe3787bcaa5.png)

right now i am directly importing the class` import Echo from '@ably/laravel-echo/src/echo';`

**Comment by sacOO7** [comment]
Okay, I will check and fix it : )
