### ISSUE TITLE
Doesn't work with Laravel Sanctum

### ISSUE THREAD

**Issue by zoranlorkovic** [ably-forks/laravel-echo#26]
### Echo Version

1.0.3

### Laravel Version

10.10

### PHP Version

8.2

### NPM Version

10.2

### Description

Hi,

To be able to work with Laravel Sanctum, we should be able to to set a custom authoriser (axis) which is predefine for a cross-domain requests, similar as we need for Pusher (please check: https://laravel.com/docs/10.x/sanctum#authorizing-private-broadcast-channels)

But this is not possible if using Laravel Echo from Ably as there isn't an option to do so and you're getting "CSRF token mismatch." error when you try to auth to private channel.

I've tried to set csrfToken and bearerToken but it didn't worked.

### Steps To Reproduce

- Install new Laravel installation
- Install Laravel Sanctum package
- Install Laravel Echo from Ably
- Follow instructions to setup Broadcast rules

**Comment by sacOO7** [comment]
@zoranlorkovic thanks for raising the issue. We will look into adding support for the same.

**Comment by KalanaPerera** [comment]
@sacOO7 do you have any planned date for the release? We are blocked with this error, any alternative solution? TIA

**Comment by sacOO7** [comment]
@KalanaPerera let me check if there is a way to use this feature without making explicit changes to the code

**Comment by sacOO7** [comment]
@zoranlorkovic @KalanaPerera It seems we already have a solution here, you need to pass `requestTokenFn` as an argument
```
echo = new Echo({
        broadcaster: 'ably',
        useTls: true,
        requestTokenFn: async (channelName: string, existingToken: string) => {
            let postData = { channel_name: channelName, token: existingToken };
            return await axios.post("/api/broadcasting/auth", postData);
        },
});
```        

Basically this code is equivalent of 
https://github.com/ably-forks/laravel-echo/blob/85f4dbcc01f8f54d5127a067a2ca1dc2f509cc22/src/channel/ably/auth.ts#L34-L49
I think we don't need to provide extra headers in case of axios. I will update README for the same.

**Comment by sacOO7** [comment]
@zoranlorkovic wait a minute, let me check on this 🙂

**Comment by sacOO7** [comment]
We have customized endpoint `api/broadcasting/auth` in case of `ably-laravel-broadcaster`. So, it will be a difference response than `pusher` one. It does expects `existing token` and `channelName`. As far as `socket_id` is concerned, it's automatically set by `axios` as a header here -> 
https://github.com/ably-forks/laravel-echo/blob/85f4dbcc01f8f54d5127a067a2ca1dc2f509cc22/src/echo.ts#L157-L165

So, it will be implicitly read by the `endpoint` internally. We should know it, at the top level everything should work fine.

**Comment by sacOO7** [comment]
Also, don't forget to star both repos https://github.com/ably/laravel-broadcaster and https://github.com/ably-forks/laravel-echo/.
Ask your colleagues to do so too :P. We are looking for devs like you to raise issues like this with us :  )

**Comment by zoranlorkovic** [comment]
Ah, you're right, sorry about that. I was looking at default Laravel `api/boradcasting/auth` endpoint.
I've just checked yours and indeed it does expect `channel_name` and `token`.

And it seems it does sends correct channel name when subscribing as I've noticed that in first call it makes to `api/broadcasting/auth` it's sending data:

`{"channel_name":"private:App.Models.User.1","token":null}`

but on every other request which is making every 45s or so it's just sending this data:

`{"channel_name":null}`

**Comment by sacOO7** [comment]
Okay, let me check that one too 👍

**Comment by sacOO7** [comment]
Hi @zoranlorkovic 
By any chance did you set token expiry as 1 minute as per https://github.com/ably/laravel-broadcaster/tree/main#configure-advanced-features ?
If that's the case, it will try to renew the token every 1 minute. In such a case, no new channel is being authenticated, rather existing channels from `existing_token` will be re-authenticated

**Comment by sacOO7** [comment]
For every new `channel.private()`(private channel)  or `channel.join()`(presence channel), it will always send `channel_name` in the request.

**Comment by sacOO7** [comment]
Okay, is this still happening after making this change 
```
        requestTokenFn: async (channelName: string, existingToken: string) => {
            let postData = { channel_name: channelName, token: existingToken };
            const res = await axios.post("/api/broadcasting/auth", postData);
            return res.data;
        },
```
Note that, we have modified the code to return `res.data` instead of `res`

**Comment by zoranlorkovic** [comment]
This seems to resolve this issue. Now there are just two requests to `api/broadcast/auth`:

First one is with data:

`{"channel_name":"private:App.Models.User.1","token":null}`

result:

{
    "token": "returnedToken"
}

Second request:

`{"channel_name":null,"token":"returnedTokenFromPreviousRequest"}`

result:

{
    "token": "returnedTokenSameAsPrevious"
}

Is this excepted result?

Also that message:
`Ably: Auth.requestToken(): token request signing call returned error; err = TypeError: undefined is not an object (evaluating 'jwtToken.split')` seems to be gone now.

**Comment by zoranlorkovic** [comment]
Ah, so sorry, don't know how I missed that additional code you've mentioned in https://github.com/ably-forks/laravel-echo/issues/26#issuecomment-1828234953 !

Repos already starred!

**Comment by sacOO7** [comment]
Thanks! Please feel free to raise more issues 👍. 
There are no bugs reported in the library so far since the first release. 
So, we are eagerly waiting for improvements that can be done to support new trends !!

**Comment by zoranlorkovic** [comment]
Thank you for your help and quick replies @sacOO7 ! 

I've almost call it a day and returned back to Pusher but your quick replies really pushed me to stay and try again. Even after you've sent the solution an hour ago :)
