### ISSUE TITLE
customInternalAttach -> authorize -> errCallback undefined?

### ISSUE THREAD

**Issue by ryzr** [ably-forks/laravel-echo#29]
### Echo Version

1.0.3

### Laravel Version

10.38.1

### PHP Version

8.2

### NPM Version

10.1

### Database Driver & Version

MySQL 8.0.35 on AWS RDS

### Description

Just a minor one, but gets a bit spammy in Sentry. There appears to be cases where the overriden channel attach method is called with an undefined errCallback. It doesn't appear to have any impact on the end user, but it does get reported in Sentry at least a few times a day

![2023-12-22_103721_TypeError i is not a function — lumin-sports-technology — arc-core-field@2x](https://github.com/ably-forks/laravel-echo/assets/9389421/455da0ba-477c-4cd9-a9cb-3e1339402c49)

https://github.com/ably-forks/laravel-echo/blob/master/src/channel/ably/attach.ts#L28

Wasn't sure if it would be fine to check if errCallback is defined before calling, or something more elaborate like this would be necessary:

https://github.com/ably/ably-js/blob/fdd5a566eafac0a7fae9592f890361a608794487/src/common/lib/client/realtimechannel.ts#L335-L339

Merry Christmas! 🎄 

### Steps To Reproduce

I haven't been able to reproduce this myself, but looking at the Sentry replays, it seems that users are idling, a request is made which 403s, and then the error above occurs.

**Comment by sacOO7** [comment]
@ryzr Thanks for reporting, seems we can modify check as 
```
if (error && errCallback)
```

**Comment by sacOO7** [comment]
Since this is a small change, you might wanna create a PR for the same.

**Comment by sacOO7** [comment]
I have merged the PR. We will see if we can do the release in the near future. If you want to use the latest code on the master branch, you can include github url for the same in `package.json` dependency.
https://dev.to/michalbryxi/github-urls-in-package-json-5412

**Comment by sacOO7** [comment]
Seems we need to fix this properly, so I opened https://github.com/ably-forks/laravel-echo/pull/31

**Comment by sacOO7** [comment]
@ryzr please do add comments there if you find anything missing

**Comment by ryzr** [comment]
Thanks @sacOO7 😄

**Comment by sacOO7** [comment]
> @ryzr I have merged the PR. We will see if we can do the release in the near future. If you want to use the latest code on the master branch, you can include github url for the same in `package.json` dependency. https://dev.to/michalbryxi/github-urls-in-package-json-5412

@ryzr do update the code as per comment and let us know if you still facing issues with sentry.

**Comment by sacOO7** [comment]
@ryzr please do star https://github.com/ably/laravel-broadcaster and this repo if your issue is addressed 👍

**Comment by ryzr** [comment]
Have done -  thanks again for all your help, I appreciate it! :-)
